version: "3"
services: 
  app.test:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: appambienteeducativofront-1.0
    ports:
      - "${APP_PORT:-80}:3000"
      - "${APP_PORTHTTPS:-443}:443"
    volumes:
     - ".:/app"
    command: ["yarn","dev","--host","0.0.0.0"]
